name: iOSTest

on:
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Sourcery
      run: sh ./setup.sh
    - name: Generate by Sourcery
      run: |
        sourcery \
          --sources AutoPreviewableTests \
          --templates Sourcery/templates \
          --output AutoPreviewableTests/CodeGenerated/AutoPreviewable.swift
    - name: Test on iOS Simulator
      run: |
        xcodebuild test \
          -project AutoPreviewable.xcodeproj \
          -scheme AutoPreviewableTests \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 11,OS=13.3"
